name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: woott07
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          git diff --cached --quiet || git commit -m "🐍 Update snake animation"
          git push
